Initial support for building with nix.
Notify-ctrl/FreeKill pull request #106
Opened 2023-04-07 19:16 UTC by xinyangli

Add flake.nix to project, so this project can be built with nix. 

Also:
- Fix a died link in README.
- Add missing dependencies in docs for Ubuntu and Arch (not tested).

2023-04-07 19:18 UTC, xinyangli commented on docs/dev/compile.rst
> +   $ sudo pacman -Sy lua sqlite swig openssl flex bison readline libgit2
没在Arch上测试过，我猜测大概是少了这两个依赖（？）

2023-04-08 01:41 UTC, Notify-ctrl requested changes

2023-04-08 01:41 UTC, Notify-ctrl commented on src/CMakeLists.txt
> +  set(LUA_LIB lua)
别改这里，lua的版本一般是不更新的，你可以考虑在构建脚本里面用sed -i替换一下cmakelists

2023-04-08 01:41 UTC, Notify-ctrl commented on flake.lock
> +{
这种lock文件应该被包含在.gitignore才对吧？没用过NixOS，不敢乱说

2023-04-08 01:41 UTC, Notify-ctrl commented on docs/dev/compile.rst
> +   $ sudo pacman -Sy lua sqlite swig openssl flex bison readline libgit2
readline是bash的依赖，在arch上绝对不可能缺少的

2023-04-08 01:41 UTC, Notify-ctrl commented on README.md
> +关于如何从头构建FreeKill，详见[编译教程](./docs/dev/compile.md)。
已经没有这个md文件了，最好链接到github.io里面的html页面

2023-04-08 01:45 UTC, Notify-ctrl commented
顺便PR描述大伙一般用中文写了，i18n这块还是没把握好

2023-04-08 02:40 UTC, xinyangli commented on flake.lock
> +{
一般为了保证build可复现，是把lock文件包含在git里的，参见[hydra](https://github.com/NixOS/hydra)

2023-04-08 02:58 UTC, xinyangli commented on src/CMakeLists.txt
> +  set(LUA_LIB lua)
> 别改这里，lua的版本一般是不更新的，你可以考虑在构建脚本里面用sed -i替换一下cmakelists

改到flake.nix里面替换了👍

2023-04-08 03:25 UTC, Notify-ctrl approved these changes

2023-04-08 03:25 UTC, merged